

name: frontend cicd

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: checkout code    
      uses: actions/checkout@v4
    - name: Notify Success
      run: echo "Docker image built and pushed successfully!"
    - name: setup node js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: install dependencies
      run: npm install
    - name: Notify Success
      run: echo "all dependency install successfully!"
