

name: frontend cicd

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - name: checkout code    
      uses: actions/checkout@v4
    - name: Notify Success
      run: echo "Docker image built and pushed successfully!"
